const updateMessage = {
  UPDATE_SENT_MESSAGE: "UPDATE_SENT_MESSAGE",
  UPDATE_DELIVERED_MESSAGE: "UPDATE_DELIVERED_MESSAGE",
  UPDATE_SEEN_MESSAGE: "UPDATE_SEEN_MESSAGE",
} as const;

export { updateMessage };
