name: Build and deploy Node.js app to Azure Web App - Showmania-backend

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      -name: Checkout repository
       uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: npm install
        run: npm install
      -name: Deploy to Azure Web App
       uses: azure/webapps-deploy@v2
       with:
         app-name: media-sharing-api
         publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
         package: .